name: fusecam

highlighter: true

markdown: redcarpet
redcarpet:
  extensions: [autolink, superscript, tables, no_intra_emphasis, footnotes]

timezone: Australia/Melbourne
encoding: utf-8

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"

exclude: docs/, lib/, scripts/
include: .htaccess

navbar: true

permalink: pretty
